### ISSUE TITLE
Stress test investigation - Message Too Long

### ISSUE THREAD

**Issue by texuf** [river-build/river#647]
### Description

Looks like decryption is failing in some cases... I but I don't understand why we're not seeing this elsewhere or in the app (maybe we are)

Hypothesis - this is a key fulfillment to a user inbox stream that encrypted way too many session keys...

At the very minimum please make this log a little better (include the stream id)

https://app.datadoghq.com/logs?query=env%3Agamma%20service%3Astress-test-node%20&agg_m=count&agg_m_source=base&agg_t=count&cols=env%2Cservice%2Ccontainer_index&event=AgAAAZEpV0ngtPEfQwAAAAAAAAAYAAAAAEFaRXBWMUlvQUFERmdDSHNyTTVkRndBQQAAACQAAAAAMDE5MTI5NWEtMmY0MS00N2U1LTk0ZTQtZDY0YWJkNjZmYWNk&fromUser=true&messageDisplay=inline&refresh_mode=sliding&saved-view-id=2705025&storage=hot&stream_sort=desc&view=spans&viz=stream&from_ts=1722972783766&to_ts=1722976383766&live=true

```
{
	"id": "AgAAAZEpV0ngtPEfQwAAAAAAAAAYAAAAAEFaRXBWMUlvQUFERmdDSHNyTTVkRndBQQAAACQAAAAAMDE5MTI5NWEtMmY0MS00N2U1LTk0ZTQtZDY0YWJkNjZmYWNk",
	"content": {
		"timestamp": "2024-08-06T20:17:52.096Z",
		"tags": [
			"managed_by:terraform",
			"source:cloudwatch",
			"env:gamma",
			"forwardername:datadogintegration-forwarderstack-rufay0-forwarder-hzhenfwrgmr6",
			"forwarder_version:3.71.0",
			"sourcecategory:aws",
			"forwarder_memorysize:1024",
			"container_index:0",
			"datadog.submission_auth:api_key"
		],
		"host": "/ecs/stress-test-node-gamma-0",
		"service": "stress-test-node",
		"message": "2024-08-06T20:17:52.096Z csb:decryption:error:4752..7e80:4eho..4ziw ProcessTick Error Error: Message too long (237798 bytes). The maximum for an encrypted message is 49152 bytes. at checkPayloadLength (/monorepo/packages/stress/dist/start.cjs:153905:11) at EncryptionDevice.decryptMessage (/monorepo/packages/stress/dist/start.cjs:154325:5) at GroupEncryptionCrypto.decryptWithDeviceKey (/monorepo/packages/stress/dist/start.cjs:154588:40) at ClientDecryptionExtensions.processNewGroupSession (/monorepo/packages/stress/dist/start.cjs:153561:41)",
		"attributes": {
			"service": "stress-test-node",
			"host": "/ecs/stress-test-node-gamma-0",
			"id": "38423636986530905654883516354382085132100074835192578048",
			"aws": {
				"awslogs": {
					"owner": "211286738967",
					"logGroup": "/ecs/stress-test-node-gamma-0",
					"logStream": "stress-test-node-gamma-0/stress-test-node/78770d8fef8f4faca14d93299a864633"
				},
				"invoked_function_arn": "arn:aws:lambda:us-east-1:211286738967:function:DatadogIntegration-ForwarderStack-RUFAY0-Forwarder-HzhENFwRgMR6",
				"function_version": "$LATEST"
			},
			"timestamp": 1722975472096
		}
	}
}
```

**Comment by miguel-nascimento** [comment]
I wasn't able to reproduce anymore. Maybe we somehow fixed?

**Comment by texuf** [comment]
Yeah lets close this after improving the error.
