### ISSUE TITLE
Increase recencyConstraintsGenerations

### ISSUE THREAD

**Issue by texuf** [river-build/river#680]
### Description

recencyConstraintsGenerations determines how far back a prevMiniblockHash can be before an event is rejected by the node. We're seeing a ton of BAD_PREV_MINIBLOCK_HASH errors in stress tests and we think that we're within normal bounds for these tests for active streams.

The value is currently 5 - maybe it should be 15 or 20

logs: https://app.datadoghq.com/logs?query=env%3Agamma%20service%3Astress-test-node%20error%20&agg_m=count&agg_m_source=base&agg_t=count&cols=env%2Cservice%2Ccontainer_index&event=AgAAAZEzPIUvhNAfQwAAAAAAAAAYAAAAAEFaRXpQSkluQUFCT2J1Y3k2MTVCdVFBQQAAACQAAAAAMDE5MTMzNDItNTczZC00Yzc4LWE4NDgtZjE0YTFiNDYwNzkz&fromUser=true&messageDisplay=inline&refresh_mode=sliding&saved-view-id=2705025&storage=hot&stream_sort=desc&view=spans&viz=stream&from_ts=1722537455806&to_ts=1723142255806&live=true

Example error:
```
2024-08-08T18:24:49.966Z csb:rpc:error AddEvent ERROR MeJjIiOEl2DZ _ConnectError: [failed_precondition] AddEvent: (24:BAD_PREV_MINIBLOCK_HASH) failed_precondition: AddEvent: localAddEvent: (24:BAD_PREV_MINIBLOCK_HASH) prevMiniblockHash did not reference a recent block event = ba61..e560 38c6..9604 expected = 7f342100cafba18deae030b6d0161d5e529a9b4eab68e3cc479dd9a39338f6ed req.Msg.StreamId = 20a38bcf15ab6b94d404c201dee9f67c6428c0ecb1826ef52f48e2e904844cff req.Msg.StreamId = 20a38bcf15ab6b94d404c201dee9f67c6428c0ecb1826ef52f48e2e904844cff at errorFromJson (/monorepo/packages/stress/dist/start.cjs:155987:18) at errorFromJsonBytes (/monorepo/packages/stress/dist/start.cjs:156013:10) at next (/monorepo/packages/stress/dist/start.cjs:156445:19) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async /monorepo/packages/stress/dist/start.cjs:156836:16 at async /monorepo/packages/stress/dist/start.cjs:156911:19 at async Object.unary (/monorepo/packages/stress/dist/start.cjs:156401:14) at async Object.addEvent (/monorepo/packages/stress/dist/start.cjs:155640:22) at async Client.makeEventWithHashAndAddToStream (/monorepo/packages/stress/dist/start.cjs:162839:33) at async Client.makeEventAndAddToStream (/monorepo/packages/stress/dist/start.cjs:162824:40) { rawMessage: 'AddEvent: (24:BAD_PREV_MINIBLOCK_HASH) failed_precondition: AddEvent: localAddEvent: (24:BAD_PREV_MINIBLOCK_HASH) prevMiniblockHash did not reference a recent block
' + '    event = ba61..e560 38c6..9604
' + '    expected = 7f342100cafba18deae030b6d0161d5e529a9b4eab68e3cc479dd9a39338f6ed
' + '    req.Msg.StreamId = 20a38bcf15ab6b94d404c201dee9f67c6428c0ecb1826ef52f48e2e904844cff
' + '    req.Msg.StreamId = 20a38bcf15ab6b94d404c201dee9f67c6428c0ecb1826ef52f48e2e904844cff', code: 9, metadata: Headers { 'accept-encoding': 'gzip', 'content-length': '501', 'content-type': 'application/json', date: 'Thu, 08 Aug 2024 18:24:49 GMT', vary: 'Origin', 'x-http-version': 'HTTP/2.0', 'x-river-error': 'BAD_PREV_MINIBLOCK_HASH', 'x-river-request-id': 'MeJjIiOEl2DZ' }, details: [], cause: undefined }
```

**Comment by texuf** [comment]
@sergekh2 this value is on chain yeah? How do we go about updating it?

**Comment by sergekh2** [comment]
After discussion works as intended
